import { test, expect } from '@playwright/test';
import { E2E_USER } from './seed';

// Use the storageState generated by globalSetup to ensure deterministic auth.
test.use({ storageState: 'e2e/.auth_state.json' });

// This used to click "Continue with Google" and assert a dashboard appeared,
// which can never pass in CI — there is no OAuth round-trip available, so the
// popup fails and the app stays on /login. It had been red on every run.
// Using a storageState that contains the dev mock localStorage entry exercises
// the same path (auth -> user doc -> ProtectedRoute -> authenticated shell).
test('signs in and reaches the authenticated app', async ({ page }) => {
  await page.goto('/');

  // ProtectedRoute sends a completed, verified profile to /referrals.
  await expect(page).toHaveURL(/\/referrals/, { timeout: 15000 });

  // The authenticated shell is rendered (header is only present inside AppLayout).
  await expect(page.getByRole('heading', { name: /ismailia health connect/i })).toBeVisible();
});

test('signed-in user can open the dashboard', async ({ page }) => {
  await page.goto('/');
  await expect(page).toHaveURL(/\/referrals/, { timeout: 15000 });

  await page.goto('/dashboard');
  await expect(page.getByRole('heading', { name: /overview/i })).toBeVisible({ timeout: 15000 });
});
