name: CI

on:
  push:
    branches: [ "main", "master", "sevensn" ]
  pull_request:
    branches: [ "main", "master", "sevensn" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci

      - name: Run Unit & Component Tests (Vitest)
        run: npm run test

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run E2E Tests (Playwright)
        run: npm run test:e2e
